version: "3.3"

services:
    db:
        image: "mysql:5.7"
        environment:
            MYSQL_ROOT_PASSWORD: Culosucio
            MYSQL_USERNAME: root
            MYSQL_PASSWORD: Culosucio
        ports:
            - "3307:3306"
        volumes:
            - db:/var/lib/mysql
    redis:
        image: "redis:4.0-alpine"
        command: redis-server
        volumes:
            - "redis:/data"
            
    admin:
        image: adminer
        ports:
            - "8080:8080"
            
    website:
        depends_on:
            - "db"
            - "redis"
        build: .
        ports:
            - "80:3000"
        restart: always
        environment:
            DB_USERNAME: root
            DB_PASSWORD: Culosucio
            DB_DATABASE: BaseDeDatosMySQL
            DB_PORT: 3306
            DB_HOST: db
            RAILS_ENV: production
            RAILS_MAX_THREADS: 5
            SECRET_KEY_BASE: CuloResucio
        volumes:
            - ".:/public"
            - "./config/docker/database.yml:/app/config/database.yml"

    #sidekiq:
    #    depends_on:
    #        - "db"
    #        - "redis"
    #    build: .
    #    command: sidekiq -C config/sidekiq.yml
    #    volumes:
    #        - ".:/app"
    #    environment:
    #        REDIS_URL: redis://redis:6379/0

volumes:
    redis:
    db:
